# Generated by Django 4.2.6 on 2023-10-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_event_fundmanager_remove_fund_alias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='is_duplicated',
            field=models.BooleanField(default=False),
        ),
    ]
