version: "3.9"
services:
  assestment-database:
    container_name: assestment-database
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=assestment
      - POSTGRES_PASSWORD=password
    ports:
      - 5431:5431
    command: -p 5431

  assestment-redis:
    container_name: assestment-redis
    image: "redis:alpine"
    ports:
      - "6379:6379"

  assestment-backend:
    container_name: assestment-backend
    image: assestment-backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: on-failure
    command: >
       bash -c "./wait-for.sh assestment-database:5431 -t 120 -- python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - PIPENV_VERBOSITY=-1
      - DATABASE_URL=postgres://assestment:password@assestment-database:5431/assestment
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - assestment-database
    volumes:
      - ../backend:/app

  assestment-celery:
    container_name: assestment-celery
    build:
      context: ../backend
    command: >
      bash -c "./wait-for.sh assestment-backend:8000 -t 120 -- celery -A src.app worker --beat --loglevel=INFO"
    environment:
      - DATABASE_URL=postgres://assestment:password@assestment-database:5431/assestment
      - REDIS_URL=redis://assestment-redis:6379/0
    depends_on:
      - assestment-redis
      - assestment-backend
    volumes:
      - ../backend:/app

  assestment-frontend:
    container_name: assestment-frontend
    image: assestment-frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://assestment:password@assestment-database:5431/assestment
    depends_on:
      - assestment-backend
      - assestment-celery
    volumes:
      - ../frontend:/app
    env_file:
      - ../frontend/.env

networks:
    default:
      name: assestment-network
